// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/test/": {
            "post": {
                "tags": [
                    "test"
                ],
                "summary": "create test",
                "parameters": [
                    {
                        "description": "User information",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateTest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/test/{id}": {
            "get": {
                "tags": [
                    "test"
                ],
                "summary": "get test by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "models.CreateTest": {
            "type": "object",
            "required": [
                "afterDesc",
                "ageCls",
                "beforeDesc",
                "desc",
                "img",
                "isActive",
                "minute",
                "name"
            ],
            "properties": {
                "afterDesc": {
                    "type": "string"
                },
                "ageCls": {
                    "type": "string"
                },
                "beforeDesc": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "exampleReport": {
                    "type": "string"
                },
                "img": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "minute": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "mind-demo-backend",
	Description:      "demo for mind",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
